import { mockFoodSearchResults } from "@/lib/mock-data";
import type { FoodSearchItem } from "@/types/food";
const DEFAULT_FOOD_API_KEY="8ceb32d6e436c07b0a87375c0b7a4b8e8816a798ed2dbc740d456d7814e08220";
const RECIPE_API_BASE="http://openapi.foodsafetykorea.go.kr/api";
const NUTRITION_API_BASE="https://apis.data.go.kr/1471000/FoodNtrCpntDbInfo02";
const NUTRITION_RESULT_LIMIT=100,SEARCH_RESULT_LIMIT=20;
interface FoodSearchMeta{dbGroupName?:string;dbClassName?:string;foodOriginName?:string}
type RankedFoodSearchItem=FoodSearchItem&{searchMeta?:FoodSearchMeta};
const processedFoodTerms=["쿠키","비스킷","크래커","케이크","마들렌","휘낭시에","쫀드기","아이스크림","소르베","스무디","주스","에이드","잼","장아찌","바이트","바크","빼빼로","콤부차","농축","도넛","마카롱","머핀","와플","빙수","크로와상","샌드위치","라떼"] as const;
const commonServingPresets=[{pattern:/^참외(?:_|$)/,grams:300,label:"1개"},{pattern:/^바나나(?:_|$)/,grams:100,label:"1개"},{pattern:/^사과(?:_|$)/,grams:250,label:"1개"},{pattern:/^배(?:_|$)/,grams:350,label:"1개"},{pattern:/^귤(?:_|$)/,grams:100,label:"1개"},{pattern:/^복숭아(?:_|$)/,grams:250,label:"1개"},{pattern:/^토마토(?:_|$)/,grams:200,label:"1개"},{pattern:/^고구마(?:_|$)/,grams:150,label:"중간 크기 1개"},{pattern:/^감자(?:_|$)/,grams:150,label:"중간 크기 1개"},{pattern:/(?:^|_)달걀(?:_|$)|(?:^|_)계란(?:_|$)/,grams:50,label:"1개"}] as const;
const synonymGroups=[["계란","달걀"],["후라이","프라이"],["볶음밥","볶음 밥"],["김치찌개","김치 찌개"],["된장찌개","된장 찌개"],["순두부찌개","순두부 찌개"],["미역국","미역 국"],["소고기무국","소고기 무국"],["떡국","떡 국"],["닭볶음탕","닭도리탕"],["수육","보쌈"]] as const;
function getApiKey(){return process.env.MFDS_API_KEY??DEFAULT_FOOD_API_KEY}
function toNumber(value:unknown){const normalized=typeof value==="string"?value.replace(/,/g,"").trim():value;const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:undefined}
function decodeXmlText(value:string){return value.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
function getXmlTagValue(row:string,tagName:string){const match=row.match(new RegExp(`<${tagName}>([\\s\\S]*?)</${tagName}>`,"i"));return match?decodeXmlText(match[1]).trim():undefined}
function inferHydrationFriendly(name:string){return /(국|탕|찌개|죽|스프|전골|미음|수프)/.test(name)}
function unique<T>(items:T[]){return[...new Set(items)]}
function buildSearchVariants(query:string){const trimmed=query.trim();if(!trimmed)return[];const compact=trimmed.replace(/\s+/g,"");const spaced=compact.replace(/찌개/g," 찌개").replace(/국/g," 국").replace(/탕/g," 탕").replace(/볶음밥/g," 볶음밥").trim();let variants=[trimmed,compact,spaced];for(const group of synonymGroups){const nextVariants:string[]=[];for(const variant of variants){let replaced=false;for(const synonym of group){if(variant.includes(synonym)){replaced=true;for(const candidate of group)nextVariants.push(variant.replaceAll(synonym,candidate))}}if(!replaced)nextVariants.push(variant)}variants=unique(nextVariants)}return unique(variants.map(v=>v.trim()).filter(Boolean).sort((a,b)=>a.length-b.length)).slice(0,8)}
function getPositiveNumber(value:unknown){const n=toNumber(value)??(typeof value==="string"?toNumber(value.replace(/,/g,"").match(/\d+(?:\.\d+)?/)?.[0]):undefined);return n&&n>0?n:undefined}
function getServingPreset(name:string,meta?:FoodSearchMeta){if(meta?.dbGroupName!=="원재료성")return undefined;return commonServingPresets.find(p=>p.pattern.test(name))}
function getSuggestedServing(item:Record<string,unknown>,name:string,meta:FoodSearchMeta){const preset=getServingPreset(name,meta);if(preset)return{suggestedServingGrams:preset.grams,suggestedServingLabel:preset.label};const one=getPositiveNumber(item.DISH_ONE_SERVING)??getPositiveNumber(item.NUTRI_AMOUNT_SERVING);if(one)return{suggestedServingGrams:one,suggestedServingLabel:meta.dbGroupName==="음식"?"1인분":"1회분"};const total=getPositiveNumber(item.Z10500);if(meta.dbGroupName==="음식"&&total&&total<=1500)return{suggestedServingGrams:total,suggestedServingLabel:"1인분"};return undefined}
function formatFoodName(name:string){return name.replace(/_씨 포함_생것$/," (씨 포함)").replace(/_씨 제거_생것$/," (씨 제거)").replace(/_생것$/,"").replaceAll("_"," · ")}
function parseRecipeXml(xml:string){const rows=[...xml.matchAll(/<row>([\s\S]*?)<\/row>/gi)];return rows.map(match=>{const row=match[1],name=getXmlTagValue(row,"RCP_NM")??"",servingSize=getXmlTagValue(row,"INFO_WGT")??"1인분";return name?{id:`recipe-${name}`,name,calories:toNumber(getXmlTagValue(row,"INFO_ENG"))??0,protein:toNumber(getXmlTagValue(row,"INFO_PRO"))??0,carbs:toNumber(getXmlTagValue(row,"INFO_CAR")),fat:toNumber(getXmlTagValue(row,"INFO_FAT")),servingSize,suggestedServingGrams:parseFloat(servingSize.replace(/,/g,""))||undefined,suggestedServingLabel:"1인분",hydrationFriendly:inferHydrationFriendly(name)}:null}).filter(Boolean) as FoodSearchItem[]}
function normalizeNutritionItems(payload:unknown):Record<string,unknown>[] {if(!payload||typeof payload!=="object")return[];const data=payload as Record<string,unknown>;const response=data.response&&typeof data.response==="object"?data.response as Record<string,unknown>:undefined;const body=(data.body??response?.body??data.FoodNtrCpntDbInfo02) as Record<string,unknown>|undefined;if(!body)return[];const items=body.items as Record<string,unknown>[]|{item?:Record<string,unknown>[]|Record<string,unknown>}|undefined;if(Array.isArray(items))return items;if(items&&typeof items==="object"&&"item" in items){const item=items.item;return Array.isArray(item)?item:item?[item]:[]}return[]}
function getServingSizeLabel(item:Record<string,unknown>){const raw=item.SERVING_SIZE??item.SERV_SIZE??item.SERVING_UNIT??item.Z10500??item.ONE_SERVING_SIZE;return raw?String(raw).trim():"1회분"}
function mapNutritionItem(item:Record<string,unknown>):RankedFoodSearchItem|null{const rawName=String(item.FOOD_NM_KR??item.DESC_KOR??"").trim();if(!rawName)return null;const searchMeta={dbGroupName:String(item.DB_GRP_NM??"").trim()||undefined,dbClassName:String(item.DB_CLASS_NM??"").trim()||undefined,foodOriginName:String(item.FOOD_OR_NM??"").trim()||undefined};return{id:`nutrition-${String(item.FOOD_CD??rawName)}`,name:formatFoodName(rawName),calories:toNumber(item.AMT_NUM1)??toNumber(item.ENERC)??toNumber(item.ENERC_KCAL)??0,protein:toNumber(item.AMT_NUM3)??toNumber(item.PROT)??toNumber(item.PROTEIN_G)??0,carbs:toNumber(item.AMT_NUM6)??toNumber(item.CHOCDF)??toNumber(item.CARBOHYDRATE_G),fat:toNumber(item.AMT_NUM4)??toNumber(item.FATCE)??toNumber(item.FAT_G),servingSize:getServingSizeLabel(item),...getSuggestedServing(item,rawName,searchMeta),hydrationFriendly:inferHydrationFriendly(rawName),searchMeta}}
async function fetchRecipeMatches(query:string){const response=await fetch(`${RECIPE_API_BASE}/${getApiKey()}/COOKRCP01/xml/1/15/RCP_NM=${encodeURIComponent(query)}`,{cache:"no-store"});if(!response.ok)throw new Error(`Recipe API request failed: ${response.status}`);return parseRecipeXml(await response.text())}
async function fetchNutritionMatches(query:string){const key=encodeURIComponent(getApiKey()),params=`serviceKey=${key}&pageNo=1&numOfRows=${NUTRITION_RESULT_LIMIT}&type=json&FOOD_NM_KR=${encodeURIComponent(query)}`;for(const url of[`${NUTRITION_API_BASE}/getFoodNtrCpntDbInq02?${params}`,`${NUTRITION_API_BASE}?${params}`]){try{const response=await fetch(url,{cache:"no-store"});if(!response.ok)continue;const items=normalizeNutritionItems(await response.json()).map(mapNutritionItem).filter(Boolean) as RankedFoodSearchItem[];if(items.length)return items}catch{continue}}return[]}
function mergeFoodResults(recipeItems:FoodSearchItem[],nutritionItems:RankedFoodSearchItem[]){const byName=new Map<string,RankedFoodSearchItem>();for(const item of nutritionItems)byName.set(item.name,item);for(const item of recipeItems){const existing=byName.get(item.name);byName.set(item.name,existing?{...existing,hydrationFriendly:existing.hydrationFriendly||item.hydrationFriendly}:{...item})}return[...byName.values()]}
function scoreFoodMatch(item:RankedFoodSearchItem,queryVariants:string[]){const compactName=item.name.replace(/\s+/g,"");let score=queryVariants.reduce((current,variant)=>{const compact=variant.replace(/\s+/g,"");if(item.name===variant||compactName===compact)return Math.max(current,140);if(item.name.startsWith(variant)||compactName.startsWith(compact))return Math.max(current,105);if(item.name.includes(variant)||compactName.includes(compact))return Math.max(current,80);return current},0);if(!score)return 0;if(item.searchMeta?.dbGroupName==="원재료성")score+=45;if(item.searchMeta?.dbClassName==="품목대표")score+=20;if(/생것|씨 포함|씨 제거/.test(item.name))score+=15;for(const term of processedFoodTerms)if(!queryVariants.some(v=>v.includes(term))&&item.name.includes(term))score-=55;const shortest=Math.min(...queryVariants.map(v=>v.replace(/\s+/g,"").length));return score-Math.min(20,Math.max(0,compactName.length-shortest)*.35)}
export async function searchMfdsFoods(query:string){const normalizedQuery=query.trim();if(!normalizedQuery)return mockFoodSearchResults.slice(0,8);const queryVariants=buildSearchVariants(normalizedQuery),nutritionQueryVariants=unique([...queryVariants,`${normalizedQuery.replace(/\s+/g,"_")}_생것`]);try{const recipeItems=(await Promise.all(queryVariants.map(fetchRecipeMatches))).flat(),nutritionItems=(await Promise.all(nutritionQueryVariants.map(fetchNutritionMatches))).flat();const merged=mergeFoodResults(recipeItems,nutritionItems).map(item=>({...item,matchScore:scoreFoodMatch(item,queryVariants)})).filter(item=>item.matchScore>0).sort((a,b)=>b.matchScore-a.matchScore||a.name.length-b.name.length).slice(0,SEARCH_RESULT_LIMIT).map(({matchScore:_matchScore,searchMeta:_searchMeta,...item})=>item);if(merged.length)return merged}catch{}return mockFoodSearchResults.filter(food=>queryVariants.some(v=>food.name.includes(v)||v.includes(food.name)))}
