import type { AppState } from "@/types/app";
import type { FoodSearchItem } from "@/types/food";

export const mockFoodSearchResults: FoodSearchItem[] = [
  {
    id: "miyeokguk",
    name: "미역국",
    calories: 62,
    protein: 3,
    carbs: 5,
    fat: 2,
    servingSize: "1그릇",
    hydrationFriendly: true,
  },
  {
    id: "bulgogi",
    name: "불고기",
    calories: 320,
    protein: 24,
    carbs: 10,
    fat: 18,
    servingSize: "1접시",
    hydrationFriendly: false,
  },
  {
    id: "rice",
    name: "흰쌀밥",
    calories: 300,
    protein: 6,
    carbs: 66,
    fat: 1,
    servingSize: "1공기",
    hydrationFriendly: false,
  },
  {
    id: "juk",
    name: "소고기죽",
    calories: 180,
    protein: 9,
    carbs: 24,
    fat: 5,
    servingSize: "1그릇",
    hydrationFriendly: true,
  },
  {
    id: "dubusoup",
    name: "두부국",
    calories: 90,
    protein: 8,
    carbs: 4,
    fat: 4,
    servingSize: "1그릇",
    hydrationFriendly: true,
  },
];

export const initialAppState: AppState = {
  profile: {
    name: "민지",
    deliveryType: "c-section",
    postpartumDay: 18,
    currentWeightKg: 64,
    targetWeightKg: 58,
    feedingType: "mixed",
  },
  today: new Date().toISOString(),
  checkIns: [
    {
      dateKey: "2026-04-05",
      postpartumDay: 17,
      sleepHours: 5.5,
      hydrationLiters: 1.8,
      painLevel: 4,
      bleedingLevel: 2,
      exerciseMinutes: 16,
      feedingType: "mixed",
      weightKg: 64.3,
    },
  ],
  weightLogs: [
    {
      dateKey: "2026-04-05",
      weightKg: 64.3,
    },
  ],
  meals: [
    {
      id: "meal-1",
      name: "미역국",
      calories: 62,
      protein: 3,
      carbs: 5,
      fat: 2,
      servingSize: "1그릇",
      hydrationFriendly: true,
      portionMultiplier: 1.5,
      category: "아침",
      source: "search",
      loggedAt: "2026-04-05T08:30:00.000Z",
    },
    {
      id: "meal-2",
      name: "불고기",
      calories: 320,
      protein: 24,
      carbs: 10,
      fat: 18,
      servingSize: "1접시",
      hydrationFriendly: false,
      portionMultiplier: 1,
      category: "점심",
      source: "search",
      loggedAt: "2026-04-05T12:10:00.000Z",
    },
    {
      id: "meal-3",
      name: "소고기죽",
      calories: 180,
      protein: 9,
      carbs: 24,
      fat: 5,
      servingSize: "1그릇",
      hydrationFriendly: true,
      portionMultiplier: 1,
      category: "저녁",
      source: "search",
      loggedAt: "2026-04-05T18:10:00.000Z",
    },
  ],
  ui: {
    authMode: "guest",
    guestSessionId: "guest-demo-session",
    guestSessionStartedAt: "2026-04-05T08:00:00.000Z",
    notificationsEnabled: true,
    darkModeEnabled: false,
    todayExercisePlanStatus: undefined,
  },
};
